[package]
name = "wlx_monitor_tui"
version = "0.1.0"
edition = "2024"

[dependencies]
color-eyre = "0.6.5"
ratatui = "0.30.0"
crossterm = "0.29"
dirs = "6"
serde = { version = "1", features = ["derive"] }
toml = "0.8"
wlx_monitors = { path = "../wlx_monitors" }
